### PR TITLE
Allow prepend

### PR DESCRIPTION
**Pull request by neo**

### CODE REVIEW

**Comment by arkon** [comment]
@neolwc Thanks, this looks good. Could you also add documentation of the option to README.md?

**Comment by neo** [comment]
@arkon done!

**Comment by neo** [comment]
When is the npm package gonna be updated? @arkon

**Comment by arkon** [comment]
@neolwc v1.3.0 was just published to NPM.

**Comment by neo** [comment]
@arkon Thanks! And thank you for creating this.

**Pull request merged**
