### PR TITLE
Port to angular library

### PR DESCRIPTION
**Pull request by rcketscientist**
Migrate to ng6 Angular library.

If interested, I'd need to go through this more carefully to ensure this aligns to previous expectations.

My goal here was to convert to a "proper" Angular library for some Ivy compiler tests I'd like to run.

If not interested feel free to decline; I won't put the extra effort to re-align the doc/lint/etc.

Edit:

A little more context.  When trying to test the Ivy compiler `ng-inline-svg` was failing to build despite running through the compatibility compiler.  It appeared this was due to the fact that this library was not Angular Package Format.  I've now confirmed in:
https://github.com/rcketscientist/ng-inline-svg/tree/ivyCompiler
that `ng-inline-svg` will indeed build with the Ivy compiler once converted to APF.  Ivy is targetted for ng9, so this is not necessarily a rush, but will be necessary eventually.

### CODE REVIEW

**Comment by arkon** [comment]
I'll look into this later, but I generally believe the boilerplate template that the CLI gives contains too much unnecessary stuff for my needs.

**Comment by MatejBivr** [comment]
any updates on this? thanks!

**Comment by rcketscientist** [comment]
I forked it and published it under `@rcketscientist`

**Comment by arkon** [comment]
I _think_ this library should now work fine with Ivy (in Angular 9+).

**Pull request closed without merging**
