### PR TITLE
solution for firefox svg breaking

### PR DESCRIPTION
**Pull request by OhScee**
https://bugzilla.mozilla.org/show_bug.cgi?id=370763
solution, exclusively for bug that occurs in windows ff
-> dynamic changing of url path will sometimes cause firefox to throw a `image corrupt or truncated` error and not draw the svg

### CODE REVIEW

**Comment by OhScee** [comment]
so sorry for making the merge, totally suppose to be for my own fork ! but might be a good idea to consider adding here...

**Comment by arkon** [comment]
No worries. I can see that basically the change here are the following lines:

```typescript
// work around
// https://bugzilla.mozilla.org/show_bug.cgi?id=370763
let el = document.getElementById('_ng2_inline_svg');
if (el) {
  el.remove();
}
```

Is there a guarantee that that ID will be present though, and be the correct item?

**Comment by OhScee** [comment]
yes, we should be setting it further down in _insertSVG
```javascript
const svgUseElement = document.createElementNS('http://www.w3.org/2000/svg', 'use');
svgUseElement.setAttributeNS('http://www.w3.org/1999/xlink', 'href', this.inlineSVG);      svgDOMElement.setAttribute('id', '_ng2_inline_svg');
svgDOMElement.appendChild(svgUseElement);
```

**Comment by arkon** [comment]
Ah, I missed that part. Unfortunately, setting the constant ID won't be the proper solution since it's possible to have multiple instances of this directive on a single page, and it would consequently result in multiple of the same IDs on the page, so removing it would be problematic.

That said, I don't quite understand what the bugzilla report is. Do you happen to be loading extremely large SVGs, so your solution is to remove it before loading a new one to prevent Firefox from failing to load too many large assets?

**Comment by OhScee** [comment]
hmm, i understand the id issue... 
the problem seems to stem from dynamic src changes; although i can't confidently pinpoint exactly what causes the issue to arise. It could be that mixed with the fact that some of my svgs are a bit larger. 
It seems as though firefox's src loading method may be overridden too soon when the src is updated, potentially creating garbage(?) which is why it throws this weird error.
Removing the svg and recreating has worked as far as i can tell. Testing with this method doesn't seem to reproduce the errors...

maybe an optional parameter to provide a unique identifier for the component in the instance that there are multiple on the page?

**Comment by arkon** [comment]
I added something similar in 5329b82, which should hopefully take care of this (v3.2.0).

**Pull request closed without merging**
